Repository sopkathon-32nd-10/IgoBossiOS, pull requests merged in 2023-05, with the labels that each got.

#2 [Setting] #1 - 프로젝트 초기 세팅
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  iOS.xcodeproj/project.pbxproj
  iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS.xcodeproj/xcuserdata/hellohidi.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/Application/AppDelegate.swift
  iOS/Application/SceneDelegate.swift
  iOS/Data/Common/VoidResult.swift
  iOS/Global/Constant/Image.swift
  iOS/Global/Constant/URLs.swift
  iOS/Global/Extension/UIButton+.swift
  iOS/Global/Extension/UICollectionReusableView+.swift
  iOS/Global/Extension/UICollectionViewCell+.swift
  iOS/Global/Extension/UIColor+.swift
  iOS/Global/Extension/UIImageView+.swift
  iOS/Global/Extension/UILabel+.swift
  iOS/Global/Extension/UITableHeaderFooterView+.swift
  iOS/Global/Extension/UITableViewCell+.swift
  iOS/Global/Extension/UITextField+.swift
  iOS/Global/Extension/UIView+.swift
  iOS/Global/Extension/UIViewController+.swift
  iOS/Info.plist
  iOS/Network/Foundation/APIConstants.swift
  iOS/Network/Foundation/AlamofireLogger.swift
  iOS/Network/Foundation/BaseAPI.swift
  iOS/Network/Foundation/BaseTargetType.swift
  iOS/Network/Foundation/Config.swift
  iOS/Network/Foundation/GenericResponse.swift
  iOS/Network/Foundation/NetworkResult.swift
  iOS/Network/Foundation/SimpleResponse.swift
  iOS/Presentation/Base/BaseViewController.swift
  iOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Resource/Assets.xcassets/Contents.json
  iOS/SceneDelegate.swift
Labels: 🐳 희재, ⚙️ Setting

#4 [Setting] #3 - 폰트 추가, 컬러 추가 , gitIgnore파일 업데이트
  .gitignore
  iOS.xcodeproj/project.pbxproj
  iOS/Global/Extension/UIColor+.swift
  iOS/Global/Extension/UIFont+.swift
  iOS/Info.plist
  iOS/Resource/Font/Pretendard-Bold.otf
  iOS/Resource/Font/Pretendard-Medium.otf
  iOS/ViewController.swift
Labels: 🐳 희재, ⚙️ Setting

#6 [Feat] #5 - Tabbar 구현
  iOS.xcodeproj/project.pbxproj
  iOS/Application/SceneDelegate.swift
  iOS/Presentation/Base/TabbarViewController.swift
  iOS/Presentation/Check/CheckViewController.swift
  iOS/Presentation/Home/HomeViewController.swift
  iOS/Presentation/Pay/PayViewController.swift
Labels: 🐳 희재, ✨ Feat

#8 [Setting] #7 - 폰트 변경
  iOS.xcodeproj/xcuserdata/hellohidi.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/Global/Extension/UIFont+.swift
Labels: 🐳 희재, ⚙️ Setting

#12 [Feat] #11 - TableView, TableViewCell 초기설정
  iOS.xcodeproj/project.pbxproj
  iOS/Data/Check/Check.swift
  iOS/Presentation/Base/BaseViewController.swift
  iOS/Presentation/Check/CheckTableViewCell.swift
  iOS/Presentation/Check/CheckViewController.swift
Labels: 🦁 희주, ✨ Feat

#15 [Feat] #10 - 마크주석 구분, 뷰 그림자 추가
  iOS.xcodeproj/project.pbxproj
  iOS/Global/Extension/UIView+.swift
  iOS/Presentation/Home/HomeViewController.swift
  iOS/Presentation/Home/View/HomeView.swift
Labels: 🦈 영민, ✨ Feat

#19 [Feat] #13 - TableView 레이아웃 설정 및 CheckViewController에 컴포넌트 추가
  iOS.xcodeproj/project.pbxproj
  iOS/Data/Check/Check.swift
  iOS/Presentation/Check/Cell/CheckTableViewCell.swift
  iOS/Presentation/Check/CheckViewController.swift
Labels: 🦁 희주, ✨ Feat

#20 [Feat] #14 - 근로 기준 계산기 UI 구현
  iOS.xcodeproj/project.pbxproj
  iOS.xcodeproj/xcuserdata/hellohidi.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/Presentation/Pay/PayViewController.swift
  iOS/Presentation/Pay/View/PayView.swift
Labels: 🐳 희재, ✨ Feat

#27 [Feat] #25 - PayViewController 동작 구현하기
  iOS/Application/SceneDelegate.swift
  iOS/Presentation/Pay/PayViewController.swift
  iOS/Presentation/Pay/View/PayView.swift
Labels: 🐳 희재, ✨ Feat

#29 [Feat] 홈뷰 구현 #17
  iOS.xcodeproj/xcshareddata/xcschemes/iOS.xcscheme
  iOS/Presentation/Home/HomeViewController.swift
Labels: 🦈 영민, ✨ Feat

#33 [Feat] #30 - 프로젝트 세팅
  iOS.xcodeproj/project.pbxproj
  iOS/Global/Constant/Image.swift
  iOS/Global/Extension/UIColor+.swift
  iOS/Global/Extension/UITabbar+.swift
  iOS/Presentation/Base/TabbarViewController.swift
  iOS/Presentation/Home/HomeViewController.swift
  iOS/Presentation/Home/View/HomeView.swift
  iOS/Presentation/Pay/PayViewController.swift
  iOS/Presentation/Pay/View/PayView.swift
  iOS/Resource/Assets.xcassets/btn_check.imageset/Contents.json
  iOS/Resource/Assets.xcassets/btn_check.imageset/Frame 7.png
  iOS/Resource/Assets.xcassets/btn_check.imageset/Frame 7@2x.png
  iOS/Resource/Assets.xcassets/btn_check.imageset/Frame 7@3x.png
  iOS/Resource/Assets.xcassets/btn_unCheck.imageset/Contents.json
  iOS/Resource/Assets.xcassets/btn_unCheck.imageset/Rectangle 10011.png
  iOS/Resource/Assets.xcassets/btn_unCheck.imageset/Rectangle 10011@2x.png
  iOS/Resource/Assets.xcassets/btn_unCheck.imageset/Rectangle 10011@3x.png
  iOS/Resource/Assets.xcassets/ic_calculate.imageset/Contents.json
  iOS/Resource/Assets.xcassets/ic_calculate.imageset/ic_calculate.png
  iOS/Resource/Assets.xcassets/ic_calculate.imageset/ic_calculate@2x.png
  iOS/Resource/Assets.xcassets/ic_calculate.imageset/ic_calculate@3x.png
  iOS/Resource/Assets.xcassets/ic_check.imageset/Contents.json
  iOS/Resource/Assets.xcassets/ic_check.imageset/ic_check.png
  iOS/Resource/Assets.xcassets/ic_check.imageset/ic_check@2x.png
  iOS/Resource/Assets.xcassets/ic_check.imageset/ic_check@3x.png
  iOS/Resource/Assets.xcassets/ic_home.imageset/Contents.json
  iOS/Resource/Assets.xcassets/ic_home.imageset/ic_home.png
  iOS/Resource/Assets.xcassets/ic_home.imageset/ic_home@2x.png
  iOS/Resource/Assets.xcassets/ic_home.imageset/ic_home@3x.png
  iOS/Resource/Assets.xcassets/logo.imageset/Contents.json
  iOS/Resource/Assets.xcassets/logo.imageset/Logo.png
  iOS/Resource/Assets.xcassets/logo.imageset/Logo@2x.png
  iOS/Resource/Assets.xcassets/logo.imageset/Logo@3x.png
  iOS/Resource/Assets.xcassets/logo_small.imageset/Contents.json
  iOS/Resource/Assets.xcassets/logo_small.imageset/Logo.png
  iOS/Resource/Assets.xcassets/logo_small.imageset/Logo@2x.png
  iOS/Resource/Assets.xcassets/logo_small.imageset/Logo@3x.png
Labels: 🐳 희재, ⚙️ Setting

#36 [Feat] #35 - 임금 계산 뷰 수정사항 반영
  iOS/Global/Extension/UITabbar+.swift
  iOS/Presentation/Base/TabbarViewController.swift
  iOS/Presentation/Pay/PayViewController.swift
  iOS/Presentation/Pay/View/PayView.swift
Labels: 🐳 희재, ✨ Feat

#38 [Feat] #32 - PayResultView 컴포넌트 추가 및 수정
  iOS/Presentation/Pay/PayResult/PayResultView.swift
  iOS/Presentation/Pay/PayResult/PayResultViewController.swift
  iOS/Resource/Assets.xcassets/btn_cancel.imageset/Contents.json
  iOS/Resource/Assets.xcassets/btn_cancel.imageset/ic_cancel.png
  iOS/Resource/Assets.xcassets/btn_cancel.imageset/ic_cancel@2x.png
  iOS/Resource/Assets.xcassets/btn_cancel.imageset/ic_cancel@3x.png
  iOS/Resource/Assets.xcassets/ic_warning.imageset/Contents.json
  iOS/Resource/Assets.xcassets/ic_warning.imageset/ic_warning.png
  iOS/Resource/Assets.xcassets/ic_warning.imageset/ic_warning@2x.png
  iOS/Resource/Assets.xcassets/ic_warning.imageset/ic_warning@3x.png
Labels: 🦖 유진, ✨ Feat

#47 [Feat] #46 - 홈, 임금 계산 서버 통신 구현 및 스플레시 화면 작업
  iOS.xcodeproj/project.pbxproj
  iOS/Application/SceneDelegate.swift
  iOS/Data/Check/Check.swift
  iOS/Data/Common/VoidResult.swift
  iOS/Global/Extension/UIImageView+.swift
  iOS/Network/Check/CheckAPI.swift
  iOS/Network/Check/CheckService.swift
  iOS/Network/Foundation/BaseAPI.swift
  iOS/Network/Foundation/BaseTargetType.swift
  iOS/Network/Foundation/SimpleResponse.swift
  iOS/Presentation/Check/Cell/CheckTableViewCell.swift
  iOS/Presentation/Check/CheckViewController.swift
  iOS/Presentation/Home/HomeView.swift
  iOS/Presentation/Home/View/HomeViewController.swift
  iOS/Presentation/Pay/PayResult/PayResultViewController.swift
  iOS/Presentation/Pay/PayViewController.swift
  iOS/Presentation/Splash/SplashView.swift
  iOS/Presentation/Splash/SplashViewController.swift
Labels: 🐳 희재, ✨ Feat
